# Dockerfile for Nginx

# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the custom Nginx configuration file into the container
COPY nginx.conf /etc/nginx/conf.d/django.conf