version: '2.2'

# Defining the compose version
services:

 nginx:
  build: ./nginx
  ports:
    - 8687:80
  depends_on:
    - myproject
  restart: "always"
 
 myproject:
  build: ./BlogApi
  command: sh -c "gunicorn BlogApi.wsgi:application --bind 0.0.0.0:8000"
  expose: 
   - 8000
  restart: "always"